name: Build Armbian
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: prepare compile tools
      run: |
          sudo apt-get -y install git
    - name: Clone source code
      run: |
          git clone https://github.com/150balbes/Build-Armbian
    - name: build
      run: |   
          cd Build-Armbian       
          ./compile.sh BOARD=“arm-64" BRANCH="current" RELEASE="buster" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" INSTALL_HEADERS="yes" BUILD_DESKTOP="no" BUILD_MINIMAL=“yes”
